name: Qodana
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v5.1.0
          - args: '-l jetbrains/qodana-jvm:2021.3-eap'
